#SPRING CONFIG SERVER CONFIGURATION
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/frsknalexis/config-server-bank-composite-microservices.git
          username: frsknalexis
          password: a06_04_1997a

#EUREKA CLIENT CONFIGURATION
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:7075/eureka/
    fetch-registry: true
    register-with-eureka: true