#APP CONFIGURATION
spring:
  application:
    name: discovery-service

server:
  port: 7075

#EUREKA SERVER CONFIGURATION
eureka:
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7075/eureka/